# Generated by Django 5.0.7 on 2024-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_track_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
