# Generated by Django 5.0.7 on 2024-08-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_release_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
