# Generated by Django 5.0.7 on 2024-08-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(max_length=100)),
                ("album_title", models.CharField(max_length=1000)),
                ("genre", models.CharField(max_length=50)),
                ("format", models.CharField(max_length=20)),
                ("discogs_release_id", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("in_wantlist", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_title", models.CharField(max_length=200)),
                ("length", models.DurationField()),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.release",
                    ),
                ),
            ],
        ),
    ]
