# Generated by Django 5.0.7 on 2024-08-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_release_image_url_release_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="style",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
