openapi: 3.0.3
info:
  title: vinylla_server
  version: 1.0.0
  description: API to help learn Rails.
paths:
  /api/inventory/releases/:
    get:
      operationId: inventory_releases_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page-size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - inventory
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedReleaseList'
          description: ''
    post:
      operationId: inventory_releases_create
      tags:
      - inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Release'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Release'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Release'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
          description: ''
  /api/inventory/releases/{id}/:
    get:
      operationId: inventory_releases_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this release.
        required: true
      tags:
      - inventory
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
          description: ''
    put:
      operationId: inventory_releases_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this release.
        required: true
      tags:
      - inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Release'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Release'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Release'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
          description: ''
    patch:
      operationId: inventory_releases_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this release.
        required: true
      tags:
      - inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedRelease'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedRelease'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedRelease'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
          description: ''
    delete:
      operationId: inventory_releases_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this release.
        required: true
      tags:
      - inventory
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/inventory/tracks/:
    get:
      operationId: inventory_tracks_list
      tags:
      - inventory
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Track'
          description: ''
    post:
      operationId: inventory_tracks_create
      tags:
      - inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Track'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Track'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Track'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
          description: ''
  /api/inventory/tracks/{id}/:
    get:
      operationId: inventory_tracks_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this track.
        required: true
      tags:
      - inventory
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
          description: ''
    put:
      operationId: inventory_tracks_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this track.
        required: true
      tags:
      - inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Track'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Track'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Track'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
          description: ''
    patch:
      operationId: inventory_tracks_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this track.
        required: true
      tags:
      - inventory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTrack'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTrack'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTrack'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
          description: ''
    delete:
      operationId: inventory_tracks_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this track.
        required: true
      tags:
      - inventory
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    PaginatedReleaseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Release'
    PatchedRelease:
      type: object
      properties:
        pk:
          type: integer
          readOnly: true
          title: ID
        artist_name:
          type: string
          readOnly: true
        album_title:
          type: string
          maxLength: 1000
        genre:
          type: string
          maxLength: 50
        style:
          type: string
          maxLength: 50
        format:
          type: string
          maxLength: 20
        discogs_release_id:
          type: string
          maxLength: 100
        year:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        in_wantlist:
          type: boolean
        image_url:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        thumbnail_url:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        tracks:
          type: string
          readOnly: true
    PatchedTrack:
      type: object
      properties:
        release:
          type: integer
        track_title:
          type: string
          maxLength: 200
        duration:
          type: string
          nullable: true
          maxLength: 10
    Release:
      type: object
      properties:
        pk:
          type: integer
          readOnly: true
          title: ID
        artist_name:
          type: string
          readOnly: true
        album_title:
          type: string
          maxLength: 1000
        genre:
          type: string
          maxLength: 50
        style:
          type: string
          maxLength: 50
        format:
          type: string
          maxLength: 20
        discogs_release_id:
          type: string
          maxLength: 100
        year:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        in_wantlist:
          type: boolean
        image_url:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        thumbnail_url:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        tracks:
          type: string
          readOnly: true
      required:
      - album_title
      - artist_name
      - discogs_release_id
      - format
      - genre
      - pk
      - price
      - tracks
      - year
    Track:
      type: object
      properties:
        release:
          type: integer
        track_title:
          type: string
          maxLength: 200
        duration:
          type: string
          nullable: true
          maxLength: 10
      required:
      - release
      - track_title
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
